<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>changed</key>
	<dict>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#all</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>all</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#comments</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#directives</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#variables</string>
					</dict>
					<dict>
						<key>include</key>
						<string>text.html.basic</string>
					</dict>
					<dict>
						<key>include</key>
						<string>source.python</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#all</string>
					</dict>
				</array>
			</dict>
			<key>comments</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>({\#[\s+|])</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.operator.tornado.comment.open</string>
							</dict>
						</dict>
						<key>contentName</key>
						<string>comment.block.tornado.template</string>
						<key>end</key>
						<string>([\s+|]\#})</string>
						<key>endCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.operator.tornado.comment.close</string>
							</dict>
						</dict>
						<key>name</key>
						<string>keyword.operator.tornado.comment</string>
					</dict>
				</array>
			</dict>
			<key>directive_apply</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>support.function.tornado.template.directive.apply</string>
							</dict>
						</dict>
						<key>match</key>
						<string>\bapply\s(\w+)</string>
						<key>name</key>
						<string>support.function.tornado.template.directive.apply</string>
					</dict>
				</array>
			</dict>
			<key>directive_autoescape</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>variable.parameter.tornado.template.directive.autoescape</string>
							</dict>
						</dict>
						<key>match</key>
						<string>\bautoescape\s(\w+)\b</string>
						<key>name</key>
						<string>support.function.tornado.template.directive.autoescape</string>
					</dict>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>constant.language.python.None</string>
							</dict>
						</dict>
						<key>match</key>
						<string>\bautoescape\s(None)\b</string>
						<key>name</key>
						<string>support.function.tornado.template.directive.autoescape</string>
					</dict>
				</array>
			</dict>
			<key>directive_block</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>variable.parameter.tornado.template.directive.block</string>
							</dict>
						</dict>
						<key>match</key>
						<string>\bblock\s+(\w+)\b</string>
						<key>name</key>
						<string>storage.type.tornado.template.directive.block</string>
					</dict>
				</array>
			</dict>
			<key>directive_comment</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>comment.block.tornado.template</string>
							</dict>
						</dict>
						<key>match</key>
						<string>comment\s+([^%}]*)</string>
						<key>name</key>
						<string>support.function.tornado.template.directive.comment</string>
					</dict>
				</array>
			</dict>
			<key>directive_conditional</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(if|elif|when)\b</string>
						<key>name</key>
						<string>entity.name.tag.tornado.template.control</string>
					</dict>
				</array>
			</dict>
			<key>directive_control</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(else|end|except|finally|try|continue|break)\b</string>
						<key>name</key>
						<string>entity.name.tag.tornado.template.control</string>
					</dict>
				</array>
			</dict>
			<key>directive_external_template</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>captures</key>
						<dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>variable.parameter.tornado.template.directive.external_template</string>
							</dict>
						</dict>
						<key>match</key>
						<string>\b(extends|include)\s+["'|]([\w\.\/\\]+)["'|]</string>
						<key>name</key>
						<string>support.function.tornado.template.directive.external_template</string>
					</dict>
				</array>
			</dict>
			<key>directive_import</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>variable.parameter.tornado.template.directive.import</string>
							</dict>
						</dict>
						<key>match</key>
						<string>\bimport\s([\w\.]+)</string>
						<key>name</key>
						<string>support.function.tornado.template.directive.import</string>
					</dict>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>variable.parameter.tornado.template.directive.from</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>variable.parameter.tornado.template.directive.import</string>
							</dict>
						</dict>
						<key>match</key>
						<string>\bfrom\s+([\w\.]+)\s+import\s([\w\.]+)</string>
						<key>name</key>
						<string>support.function.tornado.template.directive.import</string>
					</dict>
				</array>
			</dict>
			<key>directive_keyword_and_source</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(raw|module)\b</string>
						<key>name</key>
						<string>support.function.tornado.template.directive.keyword_and_source</string>
					</dict>
				</array>
			</dict>
			<key>directive_set</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>support.variable.tornado.template.directive.set</string>
							</dict>
							<key>3</key>
							<dict>
								<key>name</key>
								<string>support.parameter.tornado.template.directive.set</string>
							</dict>
						</dict>
						<key>match</key>
						<string>set\s(\w+)[\s|]=[\s|](['"|])(.*)(['"|])</string>
						<key>name</key>
						<string>storage.type.tornado.template.directive.set</string>
					</dict>
				</array>
			</dict>
			<key>directives</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>({%|{!|{{![\s+|])</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.operator.tornado.directive.open</string>
							</dict>
						</dict>
						<key>end</key>
						<string>([\s+|]!}}|!}|%})</string>
						<key>endCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.operator.tornado.directive.close</string>
							</dict>
						</dict>
						<key>name</key>
						<string>keyword.operator.tornado.directive</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#directive_comment</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#directive_conditional</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#directive_control</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#directive_apply</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#directive_autoescape</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#directive_block</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#directive_external_template</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#directive_import</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#directive_keyword_and_source</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#directive_set</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#all</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>variables</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>({{[\s|])</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.operator.tornado.expression.open</string>
							</dict>
						</dict>
						<key>contentName</key>
						<string>variable.parameter.tornado.template.expression.value</string>
						<key>end</key>
						<string>([\s|]}})</string>
						<key>endCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>keyword.operator.tornado.expression.close</string>
							</dict>
						</dict>
						<key>name</key>
						<string>keyword.operator.tornado.expression</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>source.python</string>
							</dict>
							<dict>
								<key>include</key>
								<string>#variables</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
		</dict>
	</dict>
	<key>isDelta</key>
	<true/>
	<key>uuid</key>
	<string>01DE2352-0F73-455F-8AFC-3B8564097338</string>
</dict>
</plist>
